language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.5
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1

install:
   # This is a dependency of our Django test script
 - pip install argparse --use-mirrors

 - pip install -q Django==$DJANGO_VERSION --use-mirrors

 - pip install coverage

 - pip install flake8 --use-mirrors

 - python setup.py develop

before_script:
 - flake8 --ignore=E501 sizefield

script:
 - python quicktest.py sizefield
 - coverage run quicktest.py sizefield

after_success:
 - pip install coveralls
 - coveralls

matrix:
    exclude:
        - python: 3.4
          env: DJANGO_VERSION=1.4.22
